name: Update Redmine Issue
on:
  pull_requests:
    types: [opened, closed, reopened]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: 42mate/redmine-integration-action@main
        with:
          redmine_host: ${{ secrets.REDMINE_HOST }}
          redmine_apikey: ${{ secrets.REDMINE_API_KEY}}
