# This is an example of a real workflow on WARC project.
#
# In order to apply this, you need to add the following file into
# .github/workflows folder and add the secret to your repo: REDMINE_HOST, REDMINE_API_KEY.

name: Update Redmine Issue
on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  action:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: 42mate/redmine-integration-action@main
        with:
          redmine_host: ${{ secrets.REDMINE_HOST }}
          redmine_apikey: ${{ secrets.REDMINE_API_KEY}}
